name: electra_app
description: Electra Web3 Voting App

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  walletconnect_dart: ^0.0.11
  web3dart: ^2.6.0
  http: ^0.13.4
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
